name: Awesome space picture
# Get an awesome space pic from NASA in your README!!!
on:
  schedule: 
    - cron: "0 */6 * * *"
  
  workflow_dispatch:

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: setup node 12
        uses: RndmCodeGuy20/GithubActionsGiphy@master
        with:
          node-version: 12.x
      - name: Commit and push updated file
        run: |
          git config --global user.name "rndmcodeguy"
          git config --global user.email "shantanu.mane.200@outlook.com"
          git add .
          git commit -m "docs ✨ new pic added : master"
          git push
